### ISSUE TITLE
Spikes on the vehicle path

### ISSUE THREAD

**Issue by WilliamWoo45** [RozDavid/LOL#11]
Hi @RozDavid,

I've successfully run the LOL on the `KITTI dataset`, and obtained the correct matching between the input point cloud & the map. However, I noticed there are some **spikes** along the vehicle path (shown as below), which is quite weird and not normal.

![LOL_path_problem1](https://user-images.githubusercontent.com/43923666/105172663-eb6e7100-5b5a-11eb-95d1-9486214a5af3.png)

![LOL_path_problem2](https://user-images.githubusercontent.com/43923666/105172678-f0cbbb80-5b5a-11eb-87a0-77f0c4615b61.png)

![LOL_path_problem3](https://user-images.githubusercontent.com/43923666/105172686-f5906f80-5b5a-11eb-9ca7-0fb49a74530d.png)

Any possible reason for this?

Thanks and Best Regards,
William

**Comment by RozDavid** [comment]
Hey @WilliamWoo45,

Could you share what you have in your bag files? The point of the LOL algorithm is to run Odometry and Localization on the same streaming Lidar scans. If you broadcast the vehicle transforms from the bag on the /tf topic, strange behaviours like this could happen, also there is no point for using LOL for known vehicle trajectory. 

For using LOL the correct way, one should have bag files with only the static tf transforms topic and the lidar scan topic - in your case the easiest solution could be to record a new bag file from the original Kitti dataset, where you drop the unnecessary topics.

**Comment by WilliamWoo45** [comment]
Hi @RozDavid,

Thanks for your prompt response and detailed clarification.
The method of recording a new rosbag works. 

Best Regards,
William
