### ISSUE TITLE
How to obtain a priori point cloud map

### ISSUE THREAD

**Issue by PigletPh** [RozDavid/LOL#17]
The work is excellent.But I have a problem,How to obtain a priori point cloud map?If used the LOAM to build prior point cloud  map,it's not accurate.

**Comment by RozDavid** [comment]
Hey @jiu876, 

I gave an answer to this question in #4, please check that first. I am happy to ellaborate more if you need more info. 

Cheers, 
David

**Comment by PigletPh** [comment]
> Hey @jiu876,
> 
> I gave an answer to this question in #4, please check that first. I am happy to ellaborate more if you need more info.
> 
> Cheers,
> David

Thanks for your answer.If I want to use my own data rather than KITTI,how to build the priori point cloud map quickly?

**Comment by RozDavid** [comment]
It depends if you have ground-truth information for the laser scanner or not. 

If you had a dedicated sensor setup on your robot then, the process is basically the same as I wrote earlier. 

If you don't have any information on the Lidar poses over the trajectory, you indeed need to use something like LOAM to obtain the map pointcloud registration poses. I would say though that in this case using this project doesn't make too much sense as the prerequisite is to have GT map to localize against.

**Comment by PigletPh** [comment]
Ok,thanks for your anwser!
Yours,sincerely!
