### ISSUE TITLE
Where is the paper download?

### ISSUE THREAD

**Issue by seabearlmx** [RozDavid/LOL#2]
Hi, I am a Ph.D. studying in LiDAR localization, I am very interested in your paper, but I do not know where I can download your paper, so, could you sent your paper to me by email(seabearlmx@gmail.com), thank you very much!

**Comment by RozDavid** [comment]
Hi @seabearlmx,

As the conference is still on, I am not sure how am I allowed to properly distribute the paper, but sent it to you in email. 
Also, gladly share it with anybody interested

Cheers, 
David

**Comment by narutojxl** [comment]
Hi @RozDavid :),  I'm also very interested in your paper. Could you please give us your email, i want to request the paper by email.  Or  could you please send it  to my email(18991971519@163.com), thanks your help a lot :)

**Comment by RozDavid** [comment]
Hey @narutojxl,

I just sent you our paper to you email. 
Thanks a lot for your interest and I am sure we will upload it to a public site soon, making it easier to read for everybody. 

Cheers,
David

**Comment by YangSiri** [comment]
Hi, @RozDavid 

Please count me in. I will keep it secret.

yyy8160@qq.com

Thanks

**Comment by RozDavid** [comment]
Hey @YangSiri ,

Sent it ;)
Don't have to keep it secret, I am really happy if someone is interested in that! Just trying to figure out what is the correct way to distribute it in the long term, as I am not too familiar with the legal terms. Anyway should be out there soon after ICRA or will upload it arxiv.

**Comment by sunstarchan** [comment]
https://arxiv.org/pdf/2007.01595.pdf

**Comment by aobi12138** [comment]
Hi, @RozDavid 
I`m trying compiling your project. But I can`t solve this problem. Could you please help me? After installing tensorflow_cpu by pip3, I failed to complete "catkin build tensorflow_ros_cpp". The error is as followed:
![2020-09-04 13-04-23屏幕截图](https://user-images.githubusercontent.com/28434475/92201460-325f1100-eeaf-11ea-8c8f-ee5272db2ef5.png)
Thank you!

**Comment by RozDavid** [comment]
Hey @aobi12138,

Please open new issues for new questions, this one was originally for publishing the paper with the code. 

Regarding you error, it is not enough to install tensorflow through pip, as here we need to use the C++ implementation within the catkin environment. Please follow the instruction to install and set up your workplace as detailed [here](https://github.com/tradr-project/tensorflow_ros_cpp). 

It seems to be a bit hard to find the error just from this, but as you got an error of a failed git clone, you might even have network or permission problems. Please check those first, then look into the readme of the _tensorflow_ros_cpp_ package. 

If none of those works, please open a new issue here with you Cuda version, python path for the catkin workplace, gpu type and a bit of other context that might help us trace the problem.

**Comment by aobi12138** [comment]
Hey RozDavid,
I am so glad to see your reply. Firstly, I am sorry to ask this question under an issue unrelated. It`s a rookie mistake.&nbsp;
Secondly, thanks for your advice, I will continuing trying to find a solution by following the ideas you provided. If I fail to complete that, I will open a new issue according to your requirements as soon as possible. :)





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RozDavid/LOL"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月4日(星期五) 晚上10:40
收件人:&nbsp;"RozDavid/LOL"<LOL@noreply.github.com&gt;;
抄送:&nbsp;"xujingting"<443017511@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [RozDavid/LOL] Where is the paper download? (#2)





 
Hey @aobi12138,
 
Please open new issues for new questions, this one was originally for publishing the paper with the code.
 
Regarding you error, it is not enough to install tensorflow through pip, as here we need to use the C++ implementation within the catkin environment. Please follow the instruction to install and set up your workplace as detailed here.
 
It seems to be a bit hard to find the error just from this, but as you got an error of a failed git clone, you might even have network or permission problems. Please check those first, then look into the readme of the tensorflow_ros_cpp package.
 
If none of those works, please open a new issue here with you Cuda version, python path for the catkin workplace, gpu type and a bit of other context that might help us trace the problem.
