### ISSUE TITLE
segmapper node : Roslaunch got a 'No such file or directory' error while attempting to run

### ISSUE THREAD

**Issue by jeffkimkorea-git** [RozDavid/LOL#20]
Thanks @RozDavid for the work again, and I figured out I have a problem with segmapper node. 
when I launched the file name of kitti_loam_segmap.launch ,
the error occurs like this.

Roslaunch got a 'No such file or directory' error while attempting to run:              

gdb -ex run --args /root/Catkin/LOL/devel/lib/segmapper/segmapper_node __name:=segmapper __log:=/root/.ros/log/697f507e-2b2a-11ec-bcd7-e86a64425b4b/segmapper-2.log

Please make sure that all the executables in this command exist and have
executable permission. This is often caused by a bad launch-prefix.
The traceback for the exception was written to the log file

so I tested launching the launch file without segmapper node, it goes well. Maybe only the LOAM I guess.

  <include file="$(find segmapper)/launch/segmapper.launch">
    <arg name="icp_configuration_file" value="$(find segmapper)/launch/kitti/icp_dynamic_outdoor.yaml"/>
    <arg name="icp_input_filters_file" value="$(find segmapper)/launch/kitti/input_filters_outdoor.yaml"/>
    <arg name="enable_callgrind" value="$(arg enable_callgrind)"/>
  </include>

Any idea for this? 

Sincerely, Jeff.

![image](https://user-images.githubusercontent.com/46243199/136921681-872de3a5-f6d8-4823-9db4-423931b15602.png)

**Comment by RozDavid** [comment]
Hey @jeffkimkorea-git, 

If you installation finished succesfully and you sourced your environment I suppose here shold be no error like this. 
Do you have `xterm` and `gdb` installed?

Maybe you coul try running both manually in a terminal or comment out the launch prefix from the `segmaper_node`. 

Cheers, 
David

**Comment by jeffkimkorea-git** [comment]
Installing gdb made that error clean! Thanks!

sudo apt-get install gdb
