### ISSUE TITLE
Compile the code have many problem 

### ISSUE THREAD

**Issue by Zedzou** [RozDavid/LOL#3]
hi,

Thank you for your code, but i am confuse about that:

when I run "catkin build segmapper" ,  and it is ERROR :+1: th
/home/zed/Catkin/LOL/src/laser_slam/laser_slam/include/laser_slam/common.hpp:147:83: error: cannot convert ‘std::shared_ptr<PointMatcher<float>::Transformation>’ to ‘PointMatcher<float>::Transformation*’ in initialization
               PointMatcher::get().REG(Transformation).create("RigidTransformation");

Thank you again for your outstanding contribution to the community, looking forward to your reply!

**Comment by RozDavid** [comment]
Hey @Zedzou,

Strange, I wasn't able to reproduce your error. Could you please elaborate a bit on your system? Can you check which git commit you build with the laser_slam package? Also, if you were able to build other packages in the project already?

Cheers, 
David

**Comment by Zedzou** [comment]
Sorry about that commented. I have successed in GTX1070 with cuda9.0, before that was in RTX2080 with cuda10.0 and failed. Thank you for your code.
