### ISSUE TITLE
How to make offline map?

### ISSUE THREAD

**Issue by zhuziyu-edward** [RozDavid/LOL#4]
Hi, I have a small question. How did you make offline map(which can be downloaded from dropbox)? by LOAM?

**Comment by RozDavid** [comment]
Hey @zhuziyu-edward,

We generated the maps from the Kitti ground truth odometry data and the corresponding LIDAR scans. 
Maybe the easiest way to generate it, to run the grund truth data with the [laser_slam tool](https://github.com/RozDavid/LOL/tree/master/laser_slam/laser_slam_tools/src), after you can call a service  [SaveMap](https://github.com/RozDavid/LOL/blob/master/segmap/segmapper/srv/SaveMap.srv) where you first convert from the pointclouds an octomap, then finally export as a _pcd_ file. 
The pro for this method that one can obtain a prefiltered and registered map, so we decided with this method too. 

On other approach is the most straightforward one, to register the Kitti pointcloud in the global frame, and filter it afterwards with voxelization, noise filtering and possibly ground removal. It is all depending on what is your use case for later use. 

Good luck, and please tell if I can be any more help to you.

**Comment by RozDavid** [comment]
I will close the issue now, but please fell to reopen it if you have any further questions
