### ISSUE TITLE
How to build tensorflow_ros_cpp?

### ISSUE THREAD

**Issue by zhuziyu-edward** [RozDavid/LOL#5]
Hi, I am trying to run your program, but I find it hard to compile tensorflow_ros_cpp. Could you please provide more detailed installation guide for us to follow? I am using ubuntu 16.04, do I have to manually compile tensorflow for this tensorflow_ros_cpp?

**Comment by zhuziyu-edward** [comment]
Thanks a lot, I have successfully installed and run your code.

**Comment by RozDavid** [comment]
Happy to hear that! I will close the issue now.
