### ISSUE TITLE
the command：wstool update return this:

### ISSUE THREAD

**Issue by dlutjwh** [RozDavid/LOL#6]
wstool update
Prepare updating https://github.com/ethz-asl/laser_slam.git (version None) to /Catkin/LOL/src/LOL/laser_slam
Failed to detect git presence at /home/njujwh/Catkin/LOL/src/LOL/laser_slam.
  (d)elete and replace, (a)bort, (b)ackup and replace, (s)kip:

**Comment by RozDavid** [comment]
Hey @dlutjwh,

Sorry for not responding to your issue, but your are safe to skip that submodule, as we have it included in the base repository. 
I am planning to clean up the dependencies and structure of the submodules over the chrismass holiday, will update the Installation section of the Readme too. 

Hope you were able to install after all

Cheers,
David
