### ISSUE TITLE
How to obtain the robot location inferred by LOL?

### ISSUE THREAD

**Issue by WilliamWoo45** [RozDavid/LOL#8]
Hi @RozDavid,

Thanks for providing such great work.

I have one question:
For `LOL`, how do you obtain the real-time robot location inferred by `LOL`? Did you get it by echo the `tf` relationship between the `/base_link` and `/map`, say `rosrun tf tf_echo /map /base_link`? Or is there any `rostopic` that I can check?

Thanks and Best Regards,
William

**Comment by RozDavid** [comment]
Hey @WilliamWoo45,

Glad you tried our work! 
We only broadcast poses on the tf tree, so I would suggest as you though to look for the frames. 
For that you can try `rosrun`, but I think its a bit easier to interpret if you fire up an `rviz `window, and visualize the `/tf `frames in there with `/map` as the fixed frame. There you could also see the streming clouds and the aggregated map as well. 

Hope this will help, and please continue if you need any further help!

**Comment by WilliamWoo45** [comment]
Hi @RozDavid,

Thanks for your prompt and detailed reply.
Stay safe and all the best!

Best Regards,
William
