### ISSUE TITLE
Something wrong with Segmap

### ISSUE THREAD

**Issue by yutouwd** [RozDavid/LOL#9]
Hi @RozDavid ,

Thanks for your outstanding work. I have successfully built segmapper and loam_velodyne. But when I try to run the demo, each time the segmapper process would die. The error information are as followed:

> [ WARN] [1610421711.405021814, 1317376479.456800773]: [SegMapper] Timeout while waiting between world and velodyne.
[segmapper-3] process has died [pid 14145, exit code -11, cmd /home/yutouwd/workspace/segmap/devel/lib/segmapper/segmapper_node __name:=segmapper __log:=/home/yutouwd/.ros/log/d5994fce-5481-11eb-8a50-a402b9ca85e1/segmapper-3.log].
log file: /home/yutouwd/.ros/log/d5994fce-5481-11eb-8a50-a402b9ca85e1/segmapper-3*.log

I'm using Ubuntu 16.04 and Cuda version is 9.0, Cudnn version is 7.0. Could you give some suggestions on how to fix this bug? Thank you so much.

**Comment by RozDavid** [comment]
Hey, @yutouwd,

Could you include the output of your:

`rosrun tf view_frames`

Most probaby you are not using simulated time for ros, so you can't find recent transformations between the robot and the world. Try launching your bag files with `--clock` argument

Hope this will help,
David

**Comment by yutouwd** [comment]
Hey @RozDavid ,

Thanks for your kindly reply. I have checked the launch file. The rosbag play already has ```--clock``` argument. And ```use_sim_time``` is set to ```true```. ```view_frames``` result is below:

![frames_page-0001](https://user-images.githubusercontent.com/6382417/104328435-c3618b00-5526-11eb-904c-d9da6ce33304.jpg)

I also check it in Ubuntu 18.04. (There are some bugs when I try to compile Tensorflow 1.8 with Cuda 10. So I could only run the ```kitti_loam_segmap.launch```) And it seems has the same warming ``` [SegMapper] Timeout while waiting between world and velodyne.```. But the process would not die and it can run successfully. The ```rosrun tf view_frames``` also has the same result.
